# Generated by Django 4.2.1 on 2023-06-02 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80, unique=True)),
                ('password', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('total_games_played', models.IntegerField(default=0)),
                ('wins_count', models.IntegerField(default=0)),
                ('draws_count', models.IntegerField(default=0)),
                ('losses_count', models.IntegerField(default=0)),
                ('games_waiting_move_count', models.IntegerField(default=0)),
                ('available_games_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=80, null=True, unique=True)),
                ('wg_is_creator_turn', models.BooleanField(blank=True, null=True)),
                ('wg_total_moves', models.IntegerField(default=0)),
                ('wg_board_state', models.CharField(default='', max_length=800)),
                ('wg_plays', models.CharField(default='', max_length=800)),
                ('created_at', models.CharField(max_length=80)),
                ('started_at', models.CharField(max_length=80, null=True)),
                ('ended_at', models.CharField(max_length=80, null=True)),
                ('winner_id', models.IntegerField(null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_creator', to='app_api_tic_tac_toe.customuser')),
                ('opponent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_opponent', to='app_api_tic_tac_toe.customuser')),
            ],
        ),
    ]
